CASE STUDY ON EV BATTERY VEHICLES

TASK1

1. Background

An Electric Vehicle (EV) company is testing the performance of a new battery system. During the test, sensors
collect information about the battery at different time intervals.
The following parameters are monitored:
● Temperature (°C)
● Voltage (V)
● Current (A)
● Battery Charge (%)
The company wants to analyze the collected data and determine whether the battery is operating safely and
efficiently.
You are appointed as a Battery Data Analytics Team. Analyze the data using Python, NumPy, Linear Algebra,
and Calculus.

2. Battery Sensor Data
The following readings were collected during a 6-hour test:
Time (h) Temperature (°C) Voltage (V) Current (A) Charge (%)
0 32 400 20 95
1 35 395 22 88
2 38 390 25 80
3 40 385 28 70
4 42 380 30 60
5 45 375 32 48

Task 1 — Analysis Using Python Basics
Store the given sensor readings using appropriate Python data structures, then perform the following tasks.
1. Display the sensor readings
Use a for loop to display all battery readings.

2. Identify high temperature
Apply the following condition:

If T &gt; 40 °C

Display: “High Temperature Alert”
Otherwise, display: “Temperature Normal”

3. Identify low battery
Apply the following condition:

If C &lt; 50 %

Display: “Low Battery Alert”
Otherwise, display: “Battery Charge Normal”

4. Create a function
Create a function battery_status(charge) that returns a status based on:
High, C &gt; 70
Status = Medium, 50 ≤ C ≤ 70
Low, C &lt; 50

1.

In [ ]:
# Battery sensor data
battery_data = [
    {"Time": 0, "Temperature": 32, "Voltage": 400, "Current": 20, "Charge": 95},
    {"Time": 1, "Temperature": 35, "Voltage": 395, "Current": 22, "Charge": 88},
    {"Time": 2, "Temperature": 38, "Voltage": 390, "Current": 25, "Charge": 80},
    {"Time": 3, "Temperature": 40, "Voltage": 385, "Current": 28, "Charge": 70},
    {"Time": 4, "Temperature": 42, "Voltage": 380, "Current": 30, "Charge": 60},
    {"Time": 5, "Temperature": 45, "Voltage": 375, "Current": 32, "Charge": 48}
]

# Display all battery readings using a for loop
for reading in battery_data:
    print(
        f"Time: {reading['Time']} h, "
        f"Temperature: {reading['Temperature']} °C, "
        f"Voltage: {reading['Voltage']} V, "
        f"Current: {reading['Current']} A, "
        f"Charge: {reading['Charge']}%"
    )

Time: 0 h, Temperature: 32 °C, Voltage: 400 V, Current: 20 A, Charge: 95%
Time: 1 h, Temperature: 35 °C, Voltage: 395 V, Current: 22 A, Charge: 88%
Time: 2 h, Temperature: 38 °C, Voltage: 390 V, Current: 25 A, Charge: 80%
Time: 3 h, Temperature: 40 °C, Voltage: 385 V, Current: 28 A, Charge: 70%
Time: 4 h, Temperature: 42 °C, Voltage: 380 V, Current: 30 A, Charge: 60%
Time: 5 h, Temperature: 45 °C, Voltage: 375 V, Current: 32 A, Charge: 48%


2.

In [ ]:
# Check temperature condition
for reading in battery_data:
    temperature = reading["Temperature"]

    if temperature > 40:
        print(f"Time {reading['Time']} h: High Temperature Alert")
    else:
        print(f"Time {reading['Time']} h: Temperature Normal")

Time 0 h: Temperature Normal
Time 1 h: Temperature Normal
Time 2 h: Temperature Normal
Time 3 h: Temperature Normal
Time 4 h: High Temperature Alert
Time 5 h: High Temperature Alert


3.

In [ ]:
# Check battery charge condition
for reading in battery_data:
    charge = reading["Charge"]

    if charge < 50:
        print(f"Time {reading['Time']} h: Low Battery Alert")
    else:
        print(f"Time {reading['Time']} h: Battery Charge Normal")

Time 0 h: Battery Charge Normal
Time 1 h: Battery Charge Normal
Time 2 h: Battery Charge Normal
Time 3 h: Battery Charge Normal
Time 4 h: Battery Charge Normal
Time 5 h: Low Battery Alert


4.

In [ ]:
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"


# Test the function for each reading
for reading in battery_data:
    status = battery_status(reading["Charge"])
    print(f"Time {reading['Time']} h: Charge = {reading['Charge']}%, Status = {status}")

Time 0 h: Charge = 95%, Status = High
Time 1 h: Charge = 88%, Status = High
Time 2 h: Charge = 80%, Status = High
Time 3 h: Charge = 70%, Status = Medium
Time 4 h: Charge = 60%, Status = Medium
Time 5 h: Charge = 48%, Status = Low


TASK 2

 — Analysis Using NumPy
Convert the battery data into a NumPy array. Assume the data matrix is:
┌ 32 400 20 95 ┐
│ 35 395 22 88 │
D = │ 38 390 25 80 │
│ 40 385 28 70 │
│ 42 380 30 60 │
└ 45 375 32 48 ┘
where the columns represent: [ Temperature, Voltage, Current, Charge ]
Perform the following operations:
1. Find the shape of the array
Determine the number of rows and the number of columns.
2. Calculate the average of each parameter
For example, the average temperature is:

T̄ = (T₁ + T₂ + T₃ + T₄ + T₅ + T₆) / 6
Similarly, calculate V̄ (average voltage), Ī (average current), and C̄ (average charge).
3. Find the maximum and minimum temperature
Determine T_max and T_min.

4. Extract the voltage column
Extract the column vector:

┌ 400 ┐
│ 395 │
V = │ 390 │
│ 385 │
│ 380 │
└ 375 ┘

5. Identify high-temperature readings
Find all rows satisfying:

T &gt; 40 °C

6. Identify low battery readings
Find all rows satisfying:

C &lt; 50 %

1.

In [ ]:
import numpy as np

# Battery sensor data
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

# Find the shape of the array
print("Shape of the array:", D.shape)

# Display number of rows and columns
rows, columns = D.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Shape of the array: (6, 4)
Number of rows: 6
Number of columns: 4


2.

In [ ]:
import numpy as np

# Battery sensor data
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

# Calculate averages of each parameter
average_temperature = np.mean(D[:, 0])
average_voltage = np.mean(D[:, 1])
average_current = np.mean(D[:, 2])
average_charge = np.mean(D[:, 3])

print("Average Temperature:", average_temperature, "°C")
print("Average Voltage:", average_voltage, "V")
print("Average Current:", average_current, "A")
print("Average Charge:", average_charge, "%")

Average Temperature: 38.666666666666664 °C
Average Voltage: 387.5 V
Average Current: 26.166666666666668 A
Average Charge: 73.5 %


3.

In [ ]:
# Find maximum and minimum temperature
maximum_temperature = np.max(D[:, 0])
minimum_temperature = np.min(D[:, 0])

print("Maximum Temperature:", maximum_temperature, "°C")
print("Minimum Temperature:", minimum_temperature, "°C")

Maximum Temperature: 45 °C
Minimum Temperature: 32 °C


4.

In [ ]:
# Extract the voltage column
voltage = D[:, 1]

print("Voltage column:")
print(voltage)

Voltage column:
[400 395 390 385 380 375]


5.

In [ ]:
# Identify rows where temperature > 40°C
high_temperature = D[D[:, 0] > 40]

print("High-temperature readings (T > 40°C):")
print(high_temperature)

High-temperature readings (T > 40°C):
[[ 42 380  30  60]
 [ 45 375  32  48]]


6.

In [ ]:
# Identify rows where charge < 50%
low_battery = D[D[:, 3] < 50]

print("Low-battery readings (C < 50%):")
print(low_battery)

Low-battery readings (C < 50%):
[[ 45 375  32  48]]


Task 3 — Analysis Using Linear Algebra
The company uses temperature and current to calculate a simplified Battery Stress Index.
Let the transformation matrix be:

┌ 2 1 ┐
A = │ │
└ 1 3 ┘

Consider the sensor input:

┌ T ┐ ┌ 40 ┐
X = │ │ = │ │
└ I ┘ └ 25 ┘

The output is calculated as:

Y = A X

Therefore:

┌ 2 1 ┐ ┌ 40 ┐
Y = │ │ × │ │
└ 1 3 ┘ └ 25 ┘

Students must calculate the resulting vector Y.
Additional Linear Algebra Tasks
For the matrix A above, find:
1. Transpose

Aᵀ

2. Determinant

det(A)

3. Inverse
A⁻¹, if the inverse exists.
Solving a System of Equations
The engineers need to determine two unknown battery parameters x and y. The equations are:

2x + y = 100
x + 3y = 120

Write the equations in matrix form:

A X = B

where:

┌ 2 1 ┐ ┌ x ┐ ┌ 100 ┐
A = │ │ X = │ │ B = │ │
└ 1 3 ┘ └ y ┘ └ 120 ┘

Students must solve for x and y using NumPy.

In [ ]:
import numpy as np

# Transformation matrix
A = np.array([
    [2, 1],
    [1, 3]
])

# Sensor input
X = np.array([
    [40],
    [25]
])

# Matrix multiplication
Y = A @ X

print("Output vector Y:")
print(Y)

Output vector Y:
[[105]
 [115]]


1.

In [ ]:
# Find the transpose of A
A_transpose = A.T

print("Transpose of A:")
print(A_transpose)

Transpose of A:
[[2 1]
 [1 3]]


2.

In [ ]:
det_A = np.linalg.det(A)

print("Determinant of A:", det_A)

Determinant of A: 5.000000000000001


3.

In [ ]:
A_inverse = np.linalg.inv(A)

print("Inverse of A:")
print(A_inverse)

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]


linalg

In [ ]:
A_inverse = np.linalg.inv(A)

print("Inverse of A:")
print(A_inverse)

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]


numpy code

In [ ]:
import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([
    100,
    120
])

# Solve AX = B
X = np.linalg.solve(A, B)

print("Solution:")
print(X)

print("x =", X[0])
print("y =", X[1])

Solution:
[36. 28.]
x = 36.0
y = 28.0


Task 4 — Analysis Using Calculus
The battery charge is modeled as a function of time:

C(t) = 100 − 2t − ½t²
where C(t) is the battery charge percentage and t is the time in hours.
1. Find the rate of change of battery charge
The rate at which the battery charge changes is given by dC/dt. Differentiate C(t) and determine dC/dt.
2. Calculate the discharge rate
Find the discharge rate at t = 2 and t = 5, that is, calculate:

dC/dt at t = 2 and dC/dt at t = 5

3. Interpret the result
Based on the values of dC/dt, determine whether the battery is losing charge:
● At a constant rate
● At an increasing rate
● At a decreasing rate


1.

In [ ]:
import sympy as sp

t = sp.symbols('t')

C = 100 - 2*t - sp.Rational(1, 2)*t**2

# Differentiate C(t)
dC_dt = sp.diff(C, t)

print("C(t) =", C)
print("dC/dt =", dC_dt)

C(t) = -t**2/2 - 2*t + 100
dC/dt = -t - 2


2.

In [ ]:
# Calculate discharge rates
rate_t2 = dC_dt.subs(t, 2)
rate_t5 = dC_dt.subs(t, 5)

print("dC/dt at t = 2:", rate_t2, "% per hour")
print("dC/dt at t = 5:", rate_t5, "% per hour")

dC/dt at t = 2: -4 % per hour
dC/dt at t = 5: -7 % per hour


3.

In [ ]:
battery is losing charge at an:

Increasing rate
